{% set name = "cofi" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cofi-{{ version }}.tar.gz
  sha256: 7419b62b13dffc2d15dcb68203d5389e23f7e663e3865781effb0408033f8c5f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - versioningit
  run:
    - python >=3.7
    - numpy >=1.18
    - scipy >=1.0.0
    - emcee >=3.1.0
    - arviz >=0.9.0
    - findiff >=0.7.0
    - pytorch >=1.10
    - bayesbay >=0.3.0
    - neighpy >=0.1.2

test:
  imports:
    - cofi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/inlab-geo/cofi
  summary: Common Framework for Inference
  license: BSD-2-Clause
  license_file: LICENCE
  doc_url: https://cofi.readthedocs.io/
  dev_url: https://github.com/inlab-geo/cofi

extra:
  recipe-maintainers:
    - JuergHauser
    - jwhhh
