{% set name = "cofi" %}
{% set version = "0.1.3.dev1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cofi-{{ version }}.tar.gz
  sha256: 2d82ff75baecc535a93cfdd2c417c14282c1fa32336808634f3bb1d59929806f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - versioningit
  run:
    - python >=3.7
    - numpy >=1.18
    - scipy >=1.0.0
    - emcee >=3.1.0
    - arviz >=0.9.0
    - findiff >=0.7.0
    - pytorch >=1.10

test:
  imports:
    - cofi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/inlab-geo/cofi
  summary: Common Framework for Inference
  license: BSD-2-Clause
  license_file: LICENCE
  doc_url: https://cofi.readthedocs.io/
  dev_url: https://github.com/inlab-geo/cofi

extra:
  recipe-maintainers:
    - JuergHauser
    - jwhhh
