{% set name = "cofi" %}
{% set version = "0.2.12" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/cofi-{{ version }}.tar.gz
  sha256: f9f73f1d75773e6ac8a1666d17e1d2c9ab48149a6ef1b03fb4a678791e06b488

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=42
    - versioningit
  run:
    - python >={{ python_min }}
    - numpy >=1.23.0
    - scipy >=1.9.0
    - emcee >=3.1.5
    - arviz >=0.23.0
    - findiff >=0.10.0
    - pytorch >=2.0.0
    - bayesbay >=0.3.0
    - neighpy >=0.1.5,!=0.1.8
    - mealpy >=3.0.0,<3.0.3

test:
  imports:
    - cofi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/inlab-geo/cofi
  summary: Common Framework for Inference
  license: BSD-2-Clause
  license_file: LICENCE
  doc_url: https://cofi.readthedocs.io/
  dev_url: https://github.com/inlab-geo/cofi

extra:
  recipe-maintainers:
    - JuergHauser
    - jwhhh
    - ChaiThere
